set_property IOSTANDARD LVCMOS33 [get_ports {tricol[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tricol[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tricol[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tricol[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tricol[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tricol[0]}]
set_property PACKAGE_PIN R12 [get_ports {tricol[5]}]
set_property PACKAGE_PIN M16 [get_ports {tricol[4]}]
set_property PACKAGE_PIN N15 [get_ports {tricol[3]}]
set_property PACKAGE_PIN G14 [get_ports {tricol[2]}]
set_property PACKAGE_PIN R11 [get_ports {tricol[1]}]
set_property PACKAGE_PIN N16 [get_ports {tricol[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {AN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property PACKAGE_PIN U13 [get_ports {AN[7]}]
set_property PACKAGE_PIN K2 [get_ports {AN[6]}]
set_property PACKAGE_PIN T14 [get_ports {AN[5]}]
set_property PACKAGE_PIN P14 [get_ports {AN[4]}]
set_property PACKAGE_PIN J14 [get_ports {AN[3]}]
set_property PACKAGE_PIN T9 [get_ports {AN[2]}]
set_property PACKAGE_PIN J18 [get_ports {AN[1]}]
set_property PACKAGE_PIN J17 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CA[0]}]
set_property PACKAGE_PIN T10 [get_ports {CA[7]}]
set_property PACKAGE_PIN R10 [get_ports {CA[6]}]
set_property PACKAGE_PIN K16 [get_ports {CA[5]}]
set_property PACKAGE_PIN K13 [get_ports {CA[4]}]
set_property PACKAGE_PIN P15 [get_ports {CA[3]}]
set_property PACKAGE_PIN T11 [get_ports {CA[2]}]
set_property PACKAGE_PIN L18 [get_ports {CA[1]}]
set_property PACKAGE_PIN H15 [get_ports {CA[0]}]

set_property PACKAGE_PIN V10 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports correct]
set_property PACKAGE_PIN L16 [get_ports correct]
set_property IOSTANDARD LVCMOS33 [get_ports movement]
set_property IOSTANDARD LVCMOS33 [get_ports wrong]
#set_property IOSTANDARD LVCMOS33 [get_ports active]
#set_property PACKAGE_PIN K17 [get_ports active]

#set_property SLEW SLOW [get_ports active]


set_property IOSTANDARD LVCMOS33 [get_ports active]
set_property PACKAGE_PIN V10 [get_ports active]

set_property IOSTANDARD LVCMOS33 [get_ports {current_state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_state[0]}]
set_property PACKAGE_PIN J13 [get_ports {current_state[0]}]
set_property PACKAGE_PIN N14 [get_ports {current_state[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {second[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {second[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {second[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {second[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {second[0]}]
set_property PACKAGE_PIN V16 [get_ports {second[4]}]
set_property PACKAGE_PIN U17 [get_ports {second[2]}]
set_property PACKAGE_PIN V17 [get_ports {second[1]}]
set_property PACKAGE_PIN R18 [get_ports {second[0]}]

set_property PACKAGE_PIN J15 [get_ports wrong]

set_property PACKAGE_PIN U11 [get_ports movement]

set_property PACKAGE_PIN K15 [get_ports correct_led]
set_property PACKAGE_PIN V12 [get_ports movement_led]
set_property PACKAGE_PIN H17 [get_ports wrong_led]
set_property IOSTANDARD LVCMOS33 [get_ports wrong_led]
set_property IOSTANDARD LVCMOS33 [get_ports movement_led]
set_property IOSTANDARD LVCMOS33 [get_ports correct_led]

set_property PACKAGE_PIN V11 [get_ports in_active]
set_property IOSTANDARD LVCMOS33 [get_ports in_active]
